
toolchain=gcc

all:
	$(toolchain) -Wall -Wextra -o2 -g client.c -o client
	$(toolchain) -Wall -Wextra -o2 -g server.c -o server

client:
	$(toolchain) -Wall -Wextra -o2 -g client.c -o client
server:
	$(toolchain) -Wall -Wextra -o2 -g server.c -o server

clean:
	rm client
	rm server